language: python
python:
  - 3.4
sudo: true
dist: trusty
before_install:
- sudo apt-get update # For compass, see #141
- sudo apt-get install -y firefox
install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 10 # give xvfb some time to start
- pip install -r requirements.txt
script:
- ./travis.ci.sh

